<a href="https://colab.research.google.com/github/ajw1587/Pytorch_Study/blob/main/05_Logistic_Regression_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch
!pip install torchvision

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

torch.manual_seed(1)

In [5]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [5]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([1])))

e^1 equals:  tensor([2.7183])


In [7]:
w = torch.zeros((2, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [20]:
hypothesis_1 = 1 / (1 + torch.exp(-(x_train.matmul(w) + b)))
print(hypothesis_1)
print(hypothesis_1.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [12]:
hypothesis_2 = torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis_2)
print(hypothesis_2.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [18]:
losses = -(y_train * torch.log(hypothesis) + 
           (1 - y_train) * torch.log(1 - hypothesis))
print(losses)

cost = losses.mean()
print(cost)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)
tensor(0.6931, grad_fn=<MeanBackward0>)


In [17]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [28]:
# optimizer 설정
optimizer = optim.SGD([w, b], lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  # Cost 계산
  hypothesis_3 = torch.sigmoid(x_train.matmul(w) + b)
  cost = F.binary_cross_entropy(hypothesis_3, y_train)

  # Cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/1000 Cost: 0.010295
Epoch  100/1000 Cost: 0.009824
Epoch  200/1000 Cost: 0.009394
Epoch  300/1000 Cost: 0.009001
Epoch  400/1000 Cost: 0.008639
Epoch  500/1000 Cost: 0.008305
Epoch  600/1000 Cost: 0.007996
Epoch  700/1000 Cost: 0.007709
Epoch  800/1000 Cost: 0.007442
Epoch  900/1000 Cost: 0.007193
Epoch 1000/1000 Cost: 0.006960


In [29]:
# Evaluation
# x_test가 맞지만 x_test 데이터가 따로 없어서 x_train을 사용했다.
hypothesis = torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis[:5])

tensor([[2.0477e-05],
        [1.1474e-02],
        [1.3604e-02],
        [9.8389e-01],
        [9.9977e-01]], grad_fn=<SliceBackward>)


In [30]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


In [31]:
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


In [9]:
# 실제로 사용할때!
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    return self.sigmoid(self.linear(x))

model = BinaryClassifier()

In [12]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
  # H(x) 계산
  hypothesis = model(x_train)

  # Cost 계산
  cost = F.binary_cross_entropy(hypothesis, y_train)

  # cost로 H(x) 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 10번마다 로그 출력
  if epoch % 10 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
        epoch, nb_epochs, cost.item(), accuracy*100
    ))

Epoch    0/100 Cost: 0.138461 Accuracy 100.00%
Epoch   10/100 Cost: 0.129423 Accuracy 100.00%
Epoch   20/100 Cost: 0.121517 Accuracy 100.00%
Epoch   30/100 Cost: 0.114537 Accuracy 100.00%
Epoch   40/100 Cost: 0.108331 Accuracy 100.00%
Epoch   50/100 Cost: 0.102777 Accuracy 100.00%
Epoch   60/100 Cost: 0.097778 Accuracy 100.00%
Epoch   70/100 Cost: 0.093253 Accuracy 100.00%
Epoch   80/100 Cost: 0.089138 Accuracy 100.00%
Epoch   90/100 Cost: 0.085380 Accuracy 100.00%
Epoch  100/100 Cost: 0.081933 Accuracy 100.00%
